# Generated by Django 5.2.4 on 2025-08-03 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('borrow', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrowrowRecord',
            new_name='BorrowRecord',
        ),
    ]
